//for validation
import {z} from "zod";

//id and created-at are generated by the database, so we don't need to validate them here
export const message = z.object({
    content: z.string().min(10, {message: "Message content must be at least 10 characters long"}).max(1000, {message: "Message content cannot exceed 1000 characters"}),
})
